import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Modder AI",
  description: "Terms of Service for Modder AI",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-20">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-black mb-2">Terms of Service</h1>
        <p className="text-sm text-foreground/40 mb-8">Last updated: March 30, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-foreground/70 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Modder AI (&quot;Service&quot;), operated by Modder AI (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;),
              you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">2. Description of Service</h2>
            <p>
              Modder AI provides AI-powered tools for generating Minecraft mod and plugin code, analyzing crash logs,
              and assisting with Minecraft server configuration. The Service is provided &quot;as is&quot; and may be modified at any time.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">3. User Accounts</h2>
            <p>
              You may sign in using a third-party authentication provider (e.g., Google). You are responsible for
              maintaining the security of your account. You must be at least 13 years of age to use this Service,
              or the minimum age required in your jurisdiction.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use the Service to create malicious software, malware, or exploits</li>
              <li>Attempt to reverse-engineer, decompile, or hack the Service</li>
              <li>Abuse the AI generation system by automated scraping or excessive requests</li>
              <li>Impersonate others or misrepresent your affiliation</li>
              <li>Use the Service in violation of any applicable law</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">5. Intellectual Property</h2>
            <p>
              Code generated by the Service is yours to use, modify, and distribute. However, the Service itself,
              including its design, branding, and underlying AI models, remains our property. Modder AI is not affiliated
              with Mojang Studios, Microsoft, or any third-party Minecraft platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">6. Payments & Subscriptions</h2>
            <p>
              Paid plans are billed monthly through our payment provider (Lemon Squeezy). You may cancel at any time;
              access continues through the end of your billing period. Refund requests must be made within 7 days of purchase.
              Prices are in USD and may change with 30 days prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">7. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, MODDER AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUE, WHETHER INCURRED DIRECTLY OR INDIRECTLY.
              Our total liability for any claim arising from the Service shall not exceed the amount you paid us in the
              12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
              BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
              We do not guarantee that generated code will be error-free or suitable for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">9. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless Modder AI and its officers, directors, employees, and agents
              from any claims, damages, losses, or expenses arising from your use of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">10. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for any reason, including violation of these
              Terms. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">11. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the State of Delaware,
              United States, without regard to conflict of law principles. Any disputes shall be resolved in the
              state or federal courts located in Delaware.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">12. DMCA & Copyright</h2>
            <p>
              If you believe content on the Service infringes your copyright, please contact us at{" "}
              <a href="mailto:support@modderai.net" className="text-primary-light underline">support@modderai.net</a>{" "}
              with a description of the infringement under the Digital Millennium Copyright Act (DMCA).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">13. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance.
              We will notify users of material changes via the Service or email.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-foreground mb-2">14. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{" "}
              <a href="mailto:support@modderai.net" className="text-primary-light underline">support@modderai.net</a>.
            </p>
          </section>
        </div>

        <div className="mt-10 pt-6 border-t border-border">
          <Link href="/" className="text-sm text-foreground/40 hover:text-foreground/60 transition-colors">
            ← Back to home
          </Link>
        </div>
      </div>
    </div>
  );
}
